# Generated by Powerlevel10k configuration wizard on 2023-10-26 at 18:01 PDT.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh.
# Wizard options: nerdfont-v3 + powerline, large icons, rainbow, unicode, 12h time,
# round separators, round heads, round tails, 2 lines, solid, no frame, light-ornaments,
# sparse, many icons, concise, transient_prompt, instant_prompt=verbose.
# Type `p10k configure` to generate another config.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    trans
    dir                     # current directory
    gitcli                  # asynchronous Git status
    newline
    prompt_char
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # =========================[ Line #1 ]=========================
    status                  # exit code of the last command
    command_execution_time  # duration of the last command
    background_jobs         # presence of background jobs
    context                 # user@hostname
    time
    # =========================[ Line #2 ]=========================
    newline
    direnv                  # direnv status (https://direnv.net/)
    terraform               # terraform workspace (https://www.terraform.io)
    aws                     # aws profile
    azure                   # azure account name
    gcloud                  # google cloud cli account and project
    google_app_cred         # google application credentials
    kubecontext             # current kubernetes context
  )

  typeset -g POWERLEVEL9K_MODE=nerdfont-v3
  typeset -g POWERLEVEL9K_ICON_PADDING=moderate
  typeset -g POWERLEVEL9K_ICON_BEFORE_CONTENT=
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=false

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX=
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX=

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_BACKGROUND=
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_GAP_BACKGROUND=
  if [[ $POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR != ' ' ]]; then
    typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=242
    typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_FIRST_SEGMENT_END_SYMBOL='%{%}'
    typeset -g POWERLEVEL9K_EMPTY_LINE_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='%{%}'
  fi

  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B6'
  typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B4'
  typeset -g POWERLEVEL9K_EMPTY_LINE_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=

  ################################[ prompt_char: prompt symbol ]################################
  typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=false
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=
  typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_{LEFT,RIGHT}_WHITESPACE=

  ##################################[ dir: current directory ]##################################
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
  typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
  typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
  typeset -g POWERLEVEL9K_SHORTEN_DELIMITER=
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
  typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
  local anchor_files=(
    .bzr
    .citc
    .git
    .hg
    .node-version
    .python-version
    .go-version
    .ruby-version
    .lua-version
    .java-version
    .perl-version
    .php-version
    .tool-version
    .shorten_folder_marker
    .svn
    .terraform
    CVS
    Cargo.toml
    composer.json
    go.mod
    package.json
    stack.yaml
  )
  typeset -g POWERLEVEL9K_SHORTEN_FOLDER_MARKER="(${(j:|:)anchor_files})"
  typeset -g POWERLEVEL9K_DIR_TRUNCATE_BEFORE_MARKER=false
  typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
  typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=60
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40
  typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS_PCT=50
  typeset -g POWERLEVEL9K_DIR_HYPERLINK=false
  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=v3

  # Shorten the physical DataDog repository path to ~dd.
  hash -d dd="$HOME/go/src/github.com/DataDog"

  ##########################[ gitcli: asynchronous Git status ]##########################
  typeset -g POWERLEVEL9K_GITCLI_BRANCH_ICON=' '
  typeset -g POWERLEVEL9K_GITCLI_UNTRACKED_ICON=' '
  typeset -gF POWERLEVEL9K_GITCLI_TIMEOUT_SECONDS=120

  autoload -Uz add-zsh-hook
  zmodload zsh/datetime

  _git_prompt_display_text() {
    emulate -L zsh
    local text=$1
    local -i max_width=$2
    local marker=$'\x1d'
    if [[ $text != *$marker*$marker* ]]; then
      reply=("$text" '')
      return
    fi

    local prefix=${text%%$marker*}
    local rest=${text#*$marker}
    local branch=${rest%%$marker*}
    local suffix=${rest#*$marker}
    local display=$branch

    if (( max_width > 0 && $#display > max_width )); then
      local -a parts=("${(@s:/:)display}")
      if (( $#parts >= 3 )); then
        display=${(j:/:)parts[3,-1]}
      elif (( $#parts == 2 )); then
        display=$parts[2]
      fi
      if (( $#display > max_width )); then
        if (( max_width > 2 )); then
          display="${display[1,max_width-2]}.."
        else
          display=${display[1,max_width]}
        fi
      fi
    fi

    display=${(V)display}
    reply=("${prefix}${display//\%/%%}${suffix}" "$branch")
  }

  _git_prompt_render_segment() {
    _p9k_prompt_segment prompt_gitcli_CLEAN      2 $_p9k_color1 '' 1 '$_p9k__gitcli_clean'      '$_p9k__gitcli_display_text'
    _p9k_prompt_segment prompt_gitcli_MODIFIED   3 $_p9k_color1 '' 1 '$_p9k__gitcli_modified'   '$_p9k__gitcli_display_text'
    _p9k_prompt_segment prompt_gitcli_UNTRACKED  2 $_p9k_color1 '' 1 '$_p9k__gitcli_untracked'  '$_p9k__gitcli_display_text'
    _p9k_prompt_segment prompt_gitcli_CONFLICTED 3 $_p9k_color1 '' 1 '$_p9k__gitcli_conflicted' '$_p9k__gitcli_display_text'
    _p9k_prompt_segment prompt_gitcli_REFRESHING 8 $_p9k_color1 '' 1 '$_p9k__gitcli_refreshing' '$_p9k__gitcli_display_text'
    _p9k_prompt_segment prompt_gitcli_LOADING    8 $_p9k_color1 '' 1 '$_p9k__gitcli_loading'    '$_p9k__gitcli_display_text'
  }

  prompt_gitcli() {
    local -i len=$#_p9k__prompt _p9k__has_upglob
    local raw_branch
    local -a reply

    _git_prompt_display_text "$_p9k__gitcli_text" 0
    raw_branch=$reply[2]
    if [[ -n $raw_branch ]] && (( COLUMNS > 0 )); then
      local -i dir_width=_p9k__dir_len text_width nonbranch_width max_width
      (( dir_width > POWERLEVEL9K_DIR_MAX_LENGTH )) && dir_width=POWERLEVEL9K_DIR_MAX_LENGTH
      _p9k_prompt_length "$reply[1]"
      text_width=$_p9k__ret
      nonbranch_width=$(( text_width - $#raw_branch ))
      # Reserve room for segment separators, the transient icon, the gap, and the time.
      max_width=$(( COLUMNS - dir_width - nonbranch_width - 34 ))
      (( max_width < 8 )) && max_width=8
      (( $#raw_branch > max_width )) && _git_prompt_display_text "$_p9k__gitcli_text" $max_width
    fi
    typeset -g _p9k__gitcli_display_text=$reply[1]
    _git_prompt_render_segment

    (( _p9k__has_upglob )) || typeset -g "_p9k__segment_val_${_p9k__prompt_side}[$_p9k__segment_index]"=$_p9k__prompt[len+1,-1]
  }

  _git_prompt_route_precmd() {
    local route=${PWD:A}
    if [[ $route == $_git_prompt_route_pwd ]]; then
      if [[ -n ${_p9k__gitcli_clean}${_p9k__gitcli_modified}${_p9k__gitcli_untracked}${_p9k__gitcli_conflicted} ]]; then
        typeset -g _p9k__gitcli_clean=
        typeset -g _p9k__gitcli_modified=
        typeset -g _p9k__gitcli_untracked=
        typeset -g _p9k__gitcli_conflicted=
        typeset -g _p9k__gitcli_refreshing=1
        if (( $+_git_prompt_gitcli_segment_index )); then
          typeset -g "_p9k__segment_val_${_git_prompt_gitcli_segment_side}[$_git_prompt_gitcli_segment_index]"=
        fi
      fi
      return
    fi

    typeset -g _git_prompt_route_pwd=$route
    (( ++_git_prompt_route_generation ))
    typeset -g _git_prompt_cache_git_dir=
    typeset -g _git_prompt_cache_toplevel=
    typeset -g _p9k__gitcli_text=loading
    typeset -g _p9k__gitcli_clean=
    typeset -g _p9k__gitcli_modified=
    typeset -g _p9k__gitcli_untracked=
    typeset -g _p9k__gitcli_conflicted=
    typeset -g _p9k__gitcli_refreshing=
    typeset -g _p9k__gitcli_loading=1
    if (( $+_git_prompt_gitcli_segment_index )); then
      typeset -g "_p9k__segment_val_${_git_prompt_gitcli_segment_side}[$_git_prompt_gitcli_segment_index]"=
    fi
  }

  _git_prompt_apply() {
    emulate -L zsh
    local -i generation=$1
    local route=$2 git_dir=$3 toplevel=$4 kind=$5 text=$6

    (( generation == _git_prompt_route_generation )) || return
    [[ $route == $_git_prompt_route_pwd && ${PWD:A} == $route ]] || return
    case $kind in
      absent|loading|clean|modified|untracked|conflicted) ;;
      *) return ;;
    esac

    typeset -g _git_prompt_cache_git_dir=$git_dir
    typeset -g _git_prompt_cache_toplevel=$toplevel

    local old_text=$_p9k__gitcli_text
    local old_kind=
    [[ -n $_p9k__gitcli_clean ]] && old_kind=clean
    [[ -n $_p9k__gitcli_modified ]] && old_kind=modified
    [[ -n $_p9k__gitcli_untracked ]] && old_kind=untracked
    [[ -n $_p9k__gitcli_conflicted ]] && old_kind=conflicted
    [[ -n $_p9k__gitcli_refreshing ]] && old_kind=refreshing
    [[ -n $_p9k__gitcli_loading ]] && old_kind=loading
    [[ -z $old_kind ]] && old_kind=absent

    typeset -g _p9k__gitcli_text=$text
    typeset -g _p9k__gitcli_clean=
    typeset -g _p9k__gitcli_modified=
    typeset -g _p9k__gitcli_untracked=
    typeset -g _p9k__gitcli_conflicted=
    typeset -g _p9k__gitcli_refreshing=
    typeset -g _p9k__gitcli_loading=
    case $kind in
      clean)      typeset -g _p9k__gitcli_clean=1 ;;
      modified)   typeset -g _p9k__gitcli_modified=1 ;;
      untracked)  typeset -g _p9k__gitcli_untracked=1 ;;
      conflicted) typeset -g _p9k__gitcli_conflicted=1 ;;
      loading)    typeset -g _p9k__gitcli_loading=1 ;;
    esac

    if [[ $kind != $old_kind || $text != $old_text ]]; then
      if (( $+_git_prompt_gitcli_segment_index )); then
        typeset -g "_p9k__segment_val_${_git_prompt_gitcli_segment_side}[$_git_prompt_gitcli_segment_index]"=
      fi
      reset=2
    fi
  }

  _git_prompt_run() {
    emulate -L zsh
    local -F deadline=$1 remaining
    local capture_stderr=$2 timeout_bin=
    shift 2

    if (( deadline > 0 )); then
      remaining=$(( deadline - EPOCHREALTIME ))
      (( remaining > 0 )) || return 124
      if (( $+commands[timeout] )); then
        timeout_bin=$commands[timeout]
      elif (( $+commands[gtimeout] )); then
        timeout_bin=$commands[gtimeout]
      fi
    fi

    if [[ -n $timeout_bin ]]; then
      if (( capture_stderr )); then
        LC_ALL=C "$timeout_bin" -k 1 "${remaining}s" "$@" 2>&1
      else
        LC_ALL=C "$timeout_bin" -k 1 "${remaining}s" "$@" 2>/dev/null
      fi
    elif (( capture_stderr )); then
      LC_ALL=C "$@" 2>&1
    else
      LC_ALL=C "$@" 2>/dev/null
    fi
  }

  _git_prompt_parse_track() {
    emulate -L zsh -o extended_glob
    local value=$1 ahead=0 behind=0 gone=0 rest
    case $value in
      '') ;;
      gone|'[gone]') gone=1 ;;
      'ahead '<->) ahead=${value#ahead } ;;
      'behind '<->) behind=${value#behind } ;;
      'ahead '<->', behind '<->)
        rest=${value#ahead }
        ahead=${rest%%,*}
        behind=${value##*behind }
        ;;
      *) return 1 ;;
    esac
    REPLY="$ahead $behind $gone"
  }

  _git_prompt_action() {
    emulate -L zsh -o extended_glob
    local git_dir=$1 action= progress_dir= next= last=

    if [[ -d $git_dir/rebase-merge ]]; then
      progress_dir=$git_dir/rebase-merge
      [[ -f $progress_dir/interactive ]] && action=rebase-i || action=rebase-m
      [[ ! -e $progress_dir/msgnum || -r $progress_dir/msgnum ]] || return 1
      [[ ! -e $progress_dir/end || -r $progress_dir/end ]] || return 1
      [[ -r $progress_dir/msgnum ]] && next=$(<$progress_dir/msgnum)
      [[ -r $progress_dir/end ]] && last=$(<$progress_dir/end)
    elif [[ -d $git_dir/rebase-apply ]]; then
      progress_dir=$git_dir/rebase-apply
      if [[ -f $progress_dir/rebasing ]]; then
        action=rebase
      elif [[ -f $progress_dir/applying ]]; then
        action=am
      else
        action=am/rebase
      fi
      [[ ! -e $progress_dir/next || -r $progress_dir/next ]] || return 1
      [[ ! -e $progress_dir/last || -r $progress_dir/last ]] || return 1
      [[ -r $progress_dir/next ]] && next=$(<$progress_dir/next)
      [[ -r $progress_dir/last ]] && last=$(<$progress_dir/last)
    elif [[ -f $git_dir/MERGE_HEAD ]]; then
      action=merge
    elif [[ -f $git_dir/REVERT_HEAD ]]; then
      [[ -d $git_dir/sequencer ]] && action=revert-seq || action=revert
    elif [[ -f $git_dir/CHERRY_PICK_HEAD ]]; then
      [[ -d $git_dir/sequencer ]] && action=cherry-seq || action=cherry
    elif [[ -f $git_dir/BISECT_START || -f $git_dir/BISECT_LOG ]]; then
      action=bisect
    elif [[ -d $git_dir/sequencer ]]; then
      action=action
    fi

    if [[ -n $next || -n $last ]]; then
      [[ $next == <-> && $last == <-> ]] || return 1
      action+=" $next/$last"
    fi
    REPLY=$action
  }

  _git_prompt_format() {
    emulate -L zsh -o extended_glob
    local meta='%7F' clean='%0F' modified='%0F' untracked_color='%0F' conflicted_color='%1F'
    local res escaped

    if [[ -n $local_branch ]]; then
      res+="${clean}${(g::)POWERLEVEL9K_GITCLI_BRANCH_ICON}"$'\x1d'"${local_branch}"$'\x1d'
    elif [[ -n $tag ]]; then
      escaped=${(V)tag}
      (( $#escaped > 32 )) && escaped[13,-13]='…'
      res+="${meta}#${clean}${escaped//\%/%%}"
    else
      res+="${meta}@${clean}${oid[1,8]}"
    fi

    if [[ -n $remote_branch && $remote_branch != $local_branch ]]; then
      escaped=${(V)remote_branch}
      res+="${meta}:${clean}${escaped//\%/%%}"
    fi
    [[ $commit_summary == (|*[^[:alnum:]])(wip|WIP)(|[^[:alnum:]]*) ]] && res+=" ${modified}wip"

    if (( ahead || behind )); then
      (( behind )) && res+=" ${clean}󰦗 $behind"
      (( ahead && ! behind )) && res+=' '
      (( ahead )) && res+="${clean}󰦘 $ahead"
    elif [[ -n $remote_branch ]]; then
      res+=" ${clean}="
    fi

    (( stashes )) && res+=" ${clean} $stashes"
    [[ -n $action ]] && res+=" ${conflicted_color}${action}"
    (( conflicted )) && res+=" ${conflicted_color}${conflicted}"
    (( staged )) && res+=" ${modified} $staged"
    (( unstaged )) && res+=" ${modified} $unstaged"
    (( untracked )) && res+=" ${untracked_color}${(g::)POWERLEVEL9K_GITCLI_UNTRACKED_ICON}${untracked}"
    REPLY=$res
  }

  _git_prompt_emit() {
    print -r -- "_git_prompt_apply $1 ${(q)2} ${(q)3} ${(q)4} ${(q)5} ${(q)6}"
  }

  _p9k_prompt_gitcli_init() {
    typeset -g _git_prompt_route_pwd=
    typeset -gi _git_prompt_route_generation=0
    typeset -g _git_prompt_cache_git_dir=
    typeset -g _git_prompt_cache_toplevel=
    typeset -g _p9k__gitcli_text=loading
    typeset -g _p9k__gitcli_clean=
    typeset -g _p9k__gitcli_modified=
    typeset -g _p9k__gitcli_untracked=
    typeset -g _p9k__gitcli_conflicted=
    typeset -g _p9k__gitcli_refreshing=
    typeset -g _p9k__gitcli_loading=1
    typeset -gi _git_prompt_gitcli_segment_index=$_p9k__segment_index
    typeset -g _git_prompt_gitcli_segment_side=$_p9k__prompt_side

    _git_prompt_route_precmd
    _p9k__async_segments_compute+='_p9k_gitcli_prefetch'
  }

  _p9k_gitcli_prefetch() {
    _p9k_worker_invoke gitcli \
      "_p9k_prompt_gitcli_compute $_git_prompt_route_generation ${(q)_git_prompt_route_pwd} ${(q)_git_prompt_cache_git_dir} ${(q)_git_prompt_cache_toplevel}"
  }

  _p9k_prompt_gitcli_compute() {
    _p9k_worker_async \
      "_p9k_prompt_gitcli_async $1 ${(q)2} ${(q)3} ${(q)4}" \
      _p9k_prompt_gitcli_sync
  }

  _p9k_prompt_gitcli_sync() {
    _p9k_worker_reply "$REPLY"
  }

  _p9k_prompt_gitcli_async() {
    emulate -L zsh -o extended_glob
    local -i generation=$1
    local route=$2 git_dir=$3 toplevel=$4
    local -F deadline=0
    if (( POWERLEVEL9K_GITCLI_TIMEOUT_SECONDS > 0 )) \
       && (( $+commands[timeout] || $+commands[gtimeout] )); then
      deadline=$(( EPOCHREALTIME + POWERLEVEL9K_GITCLI_TIMEOUT_SECONDS ))
    fi

    if [[ -z $git_dir || -z $toplevel ]]; then
      local revparse
      revparse=$(_git_prompt_run $deadline 1 git -C "$route" \
        rev-parse --absolute-git-dir --show-toplevel)
      if (( $? != 0 )); then
        if [[ $revparse == *'not a git repository'* ]]; then
          _git_prompt_emit $generation "$route" '' '' absent ''
        else
          _git_prompt_emit $generation "$route" '' '' loading loading
        fi
        return
      fi
      local -a revparse_lines=("${(@f)revparse}")
      if (( $#revparse_lines != 2 )); then
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      fi
      git_dir=${revparse_lines[1]:A}
      toplevel=${revparse_lines[2]:A}
    fi

    local status_output
    status_output=$(_git_prompt_run $deadline 0 git -C "$route" status \
      --porcelain=v2 --branch --show-stash --ahead-behind --no-renames)
    if (( $? != 0 )); then
      _git_prompt_emit $generation "$route" '' '' loading loading
      return
    fi

    local local_branch= oid= upstream= remote_branch= tag= commit_summary= action=
    local -i ahead=0 behind=0 stashes=0
    local -i staged=0 unstaged=0 untracked=0 conflicted=0
    local -i seen_head=0 seen_oid=0 seen_ab=0 detached=0 malformed=0
    local line value xy
    while IFS= read -r line; do
      case $line in
        '# branch.head '*)
          (( ++seen_head == 1 )) || { malformed=1; break; }
          local_branch=${line#'# branch.head '}
          if [[ $local_branch == '(detached)' ]]; then
            local_branch=
            detached=1
          fi
          ;;
        '# branch.oid '*)
          (( ++seen_oid == 1 )) || { malformed=1; break; }
          oid=${line#'# branch.oid '}
          ;;
        '# branch.upstream '*)
          [[ -z $upstream ]] || { malformed=1; break; }
          upstream=${line#'# branch.upstream '}
          ;;
        '# branch.ab '*)
          (( ++seen_ab == 1 )) || { malformed=1; break; }
          value=${line#'# branch.ab '}
          if [[ $value == +<->' '-<-> ]]; then
            ahead=${${value%% *}#+}
            behind=${${value##* }#-}
          else
            malformed=1
            break
          fi
          ;;
        '# stash '*)
          value=${line#'# stash '}
          [[ $value == <-> ]] || { malformed=1; break; }
          stashes=$value
          ;;
        '# '*) ;;
        '1 '*|'2 '*)
          xy=${line[3,4]}
          (( $#xy == 2 )) || { malformed=1; break; }
          [[ ${xy[1]} != ' ' && ${xy[1]} != '.' ]] && (( staged++ ))
          [[ ${xy[2]} != ' ' && ${xy[2]} != '.' ]] && (( unstaged++ ))
          ;;
        'u '*) (( conflicted++ )) ;;
        '? '*) (( untracked++ )) ;;
        '! '*) ;;
        *) malformed=1; break ;;
      esac
    done <<< "$status_output"

    if (( malformed || seen_head != 1 || seen_oid != 1 )) \
       || (( ! detached && ! $#local_branch )) \
       || [[ $oid != '(initial)' && ( $oid != [0-9a-f]## || ( $#oid != 40 && $#oid != 64 ) ) ]]; then
      _git_prompt_emit $generation "$route" '' '' loading loading
      return
    fi

    if [[ -n $local_branch && $oid != '(initial)' ]]; then
      local metadata
      metadata=$(_git_prompt_run $deadline 0 git -C "$route" for-each-ref --count=1 \
        --format='refname=%(refname)%0aobjectname=%(objectname)%0aupstream=%(upstream:remoteref)%0aupstream_track=%(upstream:track,nobracket)%0asubject=%(contents:subject)' \
        "refs/heads/$local_branch")
      if (( $? != 0 )); then
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      fi

      local metadata_ref= metadata_oid= metadata_upstream= upstream_track=
      local -i metadata_fields=0
      for line in "${(@f)metadata}"; do
        case $line in
          refname=*) metadata_ref=${line#refname=}; (( metadata_fields++ )) ;;
          objectname=*) metadata_oid=${line#objectname=}; (( metadata_fields++ )) ;;
          upstream=*) metadata_upstream=${line#upstream=}; (( metadata_fields++ )) ;;
          upstream_track=*) upstream_track=${line#upstream_track=}; (( metadata_fields++ )) ;;
          subject=*) commit_summary=${line#subject=}; (( metadata_fields++ )) ;;
          *) malformed=1 ;;
        esac
      done
      if (( malformed || metadata_fields != 5 )) \
         || [[ $metadata_ref != "refs/heads/$local_branch" || $metadata_oid != $oid ]]; then
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      fi

      local -a track_counts
      _git_prompt_parse_track "$upstream_track" || {
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      }
      track_counts=(${=REPLY})
      if (( track_counts[3] )); then
        ahead=0
        behind=0
      elif [[ -n $metadata_upstream ]]; then
        (( seen_ab == 1 && ahead == track_counts[1] && behind == track_counts[2] )) || {
          _git_prompt_emit $generation "$route" '' '' loading loading
          return
        }
        [[ $metadata_upstream == refs/heads/* ]] && remote_branch=${metadata_upstream#refs/heads/}
      fi

    elif [[ -z $local_branch ]]; then
      local tags
      tags=$(_git_prompt_run $deadline 0 git -C "$route" tag --points-at="$oid" --sort=refname)
      if (( $? != 0 )); then
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      fi
      [[ -n $tags ]] && tag=${${(f)tags}[-1]}
      commit_summary=$(_git_prompt_run $deadline 0 git -C "$route" show -s --format=%s "${oid}^{commit}")
      if (( $? != 0 )); then
        _git_prompt_emit $generation "$route" '' '' loading loading
        return
      fi
    fi

    _git_prompt_action "$git_dir" || {
      _git_prompt_emit $generation "$route" '' '' loading loading
      return
    }
    action=$REPLY

    _git_prompt_format
    local text=$REPLY kind
    if (( conflicted )) || [[ -n $action ]]; then
      kind=conflicted
    elif (( staged || unstaged )); then
      kind=modified
    elif (( untracked )); then
      kind=untracked
    else
      kind=clean
    fi
    _git_prompt_emit $generation "$route" "$git_dir" "$toplevel" "$kind" "$text"
  }

  ##########################[ status: exit code of the last command ]###########################
  typeset -g POWERLEVEL9K_STATUS_EXTENDED_STATES=true
  typeset -g POWERLEVEL9K_STATUS_OK=false
  typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_VISUAL_IDENTIFIER_EXPANSION='✔'
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=2
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=0
  typeset -g POWERLEVEL9K_STATUS_ERROR=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=3
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL=true
  typeset -g POWERLEVEL9K_STATUS_VERBOSE_SIGNAME=false
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=3
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=1
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE=true
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_VISUAL_IDENTIFIER_EXPANSION='✘'
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=3
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=1

  ###################[ command_execution_time: duration of the last command ]###################
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  #######################[ background_jobs: presence of background jobs ]#######################
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND=6
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=0
  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

  #######################[ direnv: direnv status (https://direnv.net/) ]########################
  typeset -g POWERLEVEL9K_DIRENV_FOREGROUND=3
  typeset -g POWERLEVEL9K_DIRENV_BACKGROUND=0

  ################[ terraform: terraform workspace (https://www.terraform.io) ]#################
  typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
  typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=('*' OTHER)
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=4
  typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=0
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_FOREGROUND=4
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_BACKGROUND=0
  typeset -g POWERLEVEL9K_TERRAFORM_VERSION_SHOW_ON_COMMAND='terraform|tf'

  #[ aws: aws profile ]#
  typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|awless|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AWS_CLASSES=('*' DEFAULT)
  typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=7
  typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=1
  typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}${P9K_AWS_REGION:+ ${P9K_AWS_REGION//\%/%%}}'

  ##########[ azure: azure account name ]##########
  typeset -g POWERLEVEL9K_AZURE_SHOW_ON_COMMAND='az|terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_AZURE_FOREGROUND=7
  typeset -g POWERLEVEL9K_AZURE_BACKGROUND=4

  ##########[ gcloud: google cloud account and project ]###########
  typeset -g POWERLEVEL9K_GCLOUD_SHOW_ON_COMMAND='gcloud|gcs|gsutil'
  typeset -g POWERLEVEL9K_GCLOUD_FOREGROUND=7
  typeset -g POWERLEVEL9K_GCLOUD_BACKGROUND=4
  typeset -g POWERLEVEL9K_GCLOUD_PARTIAL_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_ID//\%/%%}'
  typeset -g POWERLEVEL9K_GCLOUD_COMPLETE_CONTENT_EXPANSION='${P9K_GCLOUD_PROJECT_NAME//\%/%%}'
  typeset -g POWERLEVEL9K_GCLOUD_REFRESH_PROJECT_NAME_SECONDS=60

  #[ google_app_cred: google application credentials ]#
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_SHOW_ON_COMMAND='terraform|pulumi|terragrunt'
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_CLASSES=('*' DEFAULT)
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_FOREGROUND=7
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_BACKGROUND=4
  typeset -g POWERLEVEL9K_GOOGLE_APP_CRED_DEFAULT_CONTENT_EXPANSION='${P9K_GOOGLE_APP_CRED_PROJECT_ID//\%/%%}'

  ##################################[ context: user@hostname ]##################################
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=1
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_FOREGROUND=3
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=3
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE,REMOTE_SUDO}_TEMPLATE='%n@%m'
  typeset -g POWERLEVEL9K_CONTEXT_TEMPLATE='%n@%m'
  # Don't show context unless running with privileges or in SSH.
  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=

  #############[ kubecontext: current kubernetes context ]#############
  typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|kbash|helm|kubens|kubectx|oc|istioctl|kogito|k9s|helmfile|flux|fluxctl|stern|kubeseal|skaffold|kubent|kubecolor|cmctl|sparkctl'
  typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=('*' DEFAULT)
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5
  typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
  POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

  ####################################[ time: current time ]####################################
  typeset -g POWERLEVEL9K_TIME_FOREGROUND=0
  typeset -g POWERLEVEL9K_TIME_BACKGROUND=7
  typeset -g POWERLEVEL9K_TIME_FORMAT='%D{%I:%M:%S %p}'
  typeset -g POWERLEVEL9K_TIME_UPDATE_ON_COMMAND=false

  ####################################[ trans: custom segment ]####################################
  function prompt_trans() {
    p10k segment -b 212 -f 7 -i ''
  }

  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=false

  if (( $+functions[p10k] )); then
    p10k reload
    add-zsh-hook -d precmd _git_prompt_backend_precmd
    add-zsh-hook -d precmd _git_prompt_route_precmd
    add-zsh-hook -d precmd _p9k_precmd
    add-zsh-hook precmd _git_prompt_route_precmd
    add-zsh-hook precmd _p9k_precmd
  fi
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'
