sandbox_mode = "danger-full-access"
approval_policy = "never"
project_doc_fallback_filenames = []
service_tier = "default"
notify = [
  "/Users/ava.silver/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient",
  "turn-ended",
]

[projects]
"/Users/ava.silver" = { trust_level = "trusted" }
"/Users/ava.silver/dotfiles" = { trust_level = "trusted" }
"/Users/ava.silver/skills" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/datadog-api-spec" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/datadog-ci" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/dd-source" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/serverless-ci" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/serverless-remote-instrumentation" = { trust_level = "trusted" }
"/Users/ava.silver/go/src/github.com/DataDog/web-ui" = { trust_level = "trusted" }

[tui]
status_line = [
  "model-with-reasoning",
  "current-dir",
  "pull-request-number",
  "context-used",
  "context-window-size",
]
status_line_use_colors = true

[marketplaces.openai-bundled]
source_type = "local"
source = "/Users/ava.silver/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
source_type = "local"
source = "/Users/ava.silver/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[marketplaces.datadog-claude-plugins]
source_type = "git"
source = "https://github.com/DataDog/claude-marketplace.git"

[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp/authv2"

[mcp_servers.node_repl]
command = "/Users/ava.silver/Applications/Codex.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Users/ava.silver/Applications/Codex.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Users/ava.silver/Applications/Codex.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/ava.silver/.codex"
CODEX_HOME = "/Users/ava.silver/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "a3f3ca79fe2bff56076b895f1f13a8f673168160bd79d880cc34b4500e08a71c"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.609.30741"
CODEX_CLI_PATH = "/Users/ava.silver/Applications/Codex.app/Contents/Resources/codex"

[plugins]
"browser@openai-bundled" = { enabled = true }
"chrome@openai-bundled" = { enabled = true }
"dd@datadog-claude-plugins" = { enabled = true }
"documents@openai-primary-runtime" = { enabled = true }
"google-calendar@openai-curated" = { enabled = true }
"marketplace-auto-update@datadog-claude-plugins" = { enabled = true }
"presentations@openai-primary-runtime" = { enabled = true }
"sites@openai-bundled" = { enabled = true }
"spreadsheets@openai-primary-runtime" = { enabled = true }

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false
default-service-tier = "priority"

[desktop.open-in-target-preferences]
global = "zed"

[features]
js_repl = false
